### ISSUE TITLE
Actually a request/enhancement for sidebar

### ISSUE THREAD

**Issue by dinosaurfiles** [dbtek/dbyll#30]
Is there any possible way or option so that we could have a custom image background on the sidebar rather than the default one just like this? 
![screenshot from 2015-07-09 01 55 48](https://cloud.githubusercontent.com/assets/10389490/8577895/1a370b90-25de-11e5-84f7-a04ca4efbe3c.png)

**Comment by dbtek** [comment]
Liked the idea. Although this can be done with a little css, I'm working on a config based support.
